export default SweaterData = [
  {
    id: "sweater01q",
    num: 0,
    name: "sweater-blue",
    src: require("../../assets/sweater1.png"),
    altSrc: require("../../assets/sweater-blue.png"),
  },
  {
    id: "sweater02q",
    num: 1,
    name: "sweater-darkgreen",
    src: require("../../assets/sweater2.png"),
    altSrc: require("../../assets/sweater-darkgreen.png"),
  },
  {
    id: "sweater03q",
    num: 2,
    name: "sweater-white1",
    src: require("../../assets/sweater3.png"),
    altSrc: require("../../assets/sweater-white.png"),
  },
  {
    id: "sweater04q",
    num: 3,
    name: "sweater-red",
    src: require("../../assets/sweater4.png"),
    altSrc: require("../../assets/sweater-red.png"),
  },
  {
    id: "sweater05q",
    num: 4,
    name: "sweater-green",
    src: require("../../assets/sweater5.png"),
    altSrc: require("../../assets/sweater-green.png"),
  },
  {
    id: "sweater06q",
    num: 5,
    name: "sweater-white2",
    src: require("../../assets/sweater6.png"),
    altSrc: require("../../assets/sweater-white.png"),
  },
  {
    id: "sweater07q",
    num: 6,
    name: "sweater-beige",
    src: require("../../assets/sweater7.png"),
    altSrc: require("../../assets/sweater-beige.png"),
  },
  {
    id: "sweater08q",
    num: 7,
    name: "sweater-lightgreen",
    src: require("../../assets/sweater8.png"),
    altSrc: require("../../assets/sweater-lightgreen.png"),
  },
  {
    id: "sweater09q",
    num: 8,
    name: "sweater-maroon",
    src: require("../../assets/sweater9.png"),
    altSrc: require("../../assets/sweater-maroon.png"),
  },
  {
    id: "sweater10q",
    num: 9,
    name: "sweater-green2",
    src: require("../../assets/sweater10.png"),
    altSrc: require("../../assets/sweater-green2.png"),
  },
  {
    id: "sweater11q",
    num: 10,
    name: "sweater-blue",
    src: require("../../assets/sweater11.png"),
    altSrc: require("../../assets/sweater-blue.png"),
  },
  {
    id: "sweater12q",
    num: 11,
    name: "sweater-lightblue",
    src: require("../../assets/sweater12.png"),
    altSrc: require("../../assets/sweater-lightblue.png"),
  },
];
